// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetComponentById(arg1) {
  return window['go']['main']['App']['GetComponentById'](arg1);
}

export function GetTokens() {
  return window['go']['main']['App']['GetTokens']();
}

export function LoadComponentsFromApi(arg1) {
  return window['go']['main']['App']['LoadComponentsFromApi'](arg1);
}
