// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {figma} from '../models';

export function GetTokens():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function LoadComponentsFromApi(arg1:main.Config):Promise<Record<string, figma.Element>>;
